name: CMake

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release, Debug]

    runs-on: ${{ matrix.os }}

    steps:
#    - name: Install dependencies
#      run: sudo apt-get update && sudo apt-get install libthrift-dev net-tools
#
#    - name: Install Boost
#      run: > # make this a script or sth
#        wget --quiet https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2 &&
#        tar xjf boost_1_75_0.tar.bz2 &&
#        rm boost_1_75_0.tar.bz2 &&
#        cd boost_1_75_0 &&
#        ./bootstrap.sh &&
#        ./b2 address-model=64 --with-thread --with-chrono &&
#        sudo ./b2 address-model=64 --with-thread --with-chrono install &&
#        cd .. &&
#        sudo rm -rf boost_1_75_0

    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Demo
      run: echo "Build type is ${{ matrix.build_type }}"

    - name: CWD
      run: pwd

#    - name: Configure CMake
#      # Use a bash shell so we can use the same syntax for environment variable
#      # access regardless of the host operating system
#      shell: bash
#      working-directory: ${{github.workspace}}/build
#      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON
#
#    - name: Build
#      working-directory: ${{github.workspace}}/build
#      shell: bash
#      # Execute the build.  You can specify a specific target with "--target <NAME>"
#      run: cmake --build . --config $BUILD_TYPE --parallel
#
#    - name: Install
#      working-directory: ${{github.workspace}}/build
#      shell: bash
#      run: sudo cmake --build . --target install --config $BUILD_TYPE
#
#    - name: Start RC
#      working-directory: ${{github.workspace}}
#      shell: bash
#      env:
#        HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
#      run: bash ./scripts/start-rc.sh
#
#    - name: Run tests
#      working-directory: ${{github.workspace}}
#      shell: bash
#      run: ./build/hazelcast/test/src/client_test