name: CMake

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies on Ubuntu
      if: ${{ runner.os == 'Linux' }}
      run: >
        sudo apt-get update &&
        sudo apt-get install net-tools libthrift-dev libssl-dev

    - name: Install dependencies on macOS
      if: ${{ runner.os == 'macOS' }}
      run: brew install bison  # required for thrift

    - uses: actions/checkout@v2

    - name: Download and bootstrap vcpkg
      run: >
        git clone https://github.com/microsoft/vcpkg && # TODO freeze commit
        ./vcpkg/bootstrap-vcpkg.sh &&
        ./vcpkg/vcpkg install boost openssl thrift

#
#    - name: Install Boost
#      run: > # make this a script or sth
#        wget --quiet https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2 &&
#        tar xjf boost_1_75_0.tar.bz2 &&
#        rm boost_1_75_0.tar.bz2 &&
#        cd boost_1_75_0 &&
#        ./bootstrap.sh &&
#        ./b2 address-model=64 --with-thread --with-chrono &&
#        sudo ./b2 address-model=64 --with-thread --with-chrono install &&
#        cd .. &&
#        sudo rm -rf boost_1_75_0

    - name: Create build directory
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Configure
      working-directory: ${{ github.workspace }}/build
      run: >
        cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
                 -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                 -DBUILD_TESTS=ON

#
#    - name: Build
#      working-directory: ${{github.workspace}}/build
#      shell: bash
#      # Execute the build.  You can specify a specific target with "--target <NAME>"
#      run: cmake --build . --config $BUILD_TYPE --parallel
#
#    - name: Install
#      working-directory: ${{github.workspace}}/build
#      shell: bash
#      run: sudo cmake --build . --target install --config $BUILD_TYPE
#
#    - name: Start RC
#      working-directory: ${{github.workspace}}
#      shell: bash
#      env:
#        HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
#      run: bash ./scripts/start-rc.sh
#
#    - name: Run tests
#      working-directory: ${{github.workspace}}
#      shell: bash
#      run: ./build/hazelcast/test/src/client_test