name: Codestyle

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Necessary Packages
      run: sudo apt-get install clang-format

    - uses: actions/checkout@v2

    - name: Check Formatting
      working-directory: $GITHUB_WORKSPACE
      run: pwd

