name: Codestyle

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Necessary Packages
      run: sudo apt-get install clang-format

    - uses: actions/checkout@v2

    - name: Print WD 1
      working-directory: ${{github.workspace}}
      run: pwd
    
    - name: Print WD 2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: pwd

