name: nightly-Ubuntu-x86_64

on: [ push ]

jobs:
  nightly-Ubuntu-x86_64:
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Debug ]
        library_type: [ SHARED ]
        with_openssl: [ OFF ]

    runs-on: ubuntu-latest

    steps:
      - name: Install Necessary Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y net-tools libssl-dev

      - uses: actions/checkout@v2

      - name: Install Boost
        run: |
          sudo ./scripts/install-boost.sh 1.75.0

      - name: Install Thrift
        run: |
          sudo ./scripts/install-thrift.sh 0.13.0

      - name: Build, Install, Test & Verify
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
          LIBRARY_TYPE: ${{ matrix.library_type }}
          WITH_OPENSSL: ${{ matrix.with_openssl }}
          COVERAGE: OFF
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        run: |
          ./scripts/do-all-unix.sh
