name: Nightly-Linux

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [ 32, 64 ]
        build_type: [ Debug, Release ]
        library_type: [ SHARED, STATIC ]
        with_openssl: [ OFF ]  # TODO add ON after adding aws key

    runs-on: ubuntu-latest
    container: ./docker/hazelcast-fedora-x86_64

    steps:
      - uses: actions/checkout@v2

      - name: Build, Install, Test & Verify
        env:
          BIT_VERSION: ${{ matrix.arch }}
          BUILD_TYPE: ${{ matrix.build_type }}
          LIBRARY_TYPE: ${{ matrix.library_type }}
          WITH_OPENSSL: ${{ matrix.with_openssl }}
          COVERAGE: OFF
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        run: ./scripts/do-all-unix.sh
