name: nightly-macOS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly-macOS:
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Debug, Release ]
        library_type: [ SHARED, STATIC ]
        with_openssl: [ OFF, ON ]

    runs-on: macos-latest

    steps:
      - name: Install Dependencies
        run: |
          brew install boost openssl thrift

      - uses: actions/checkout@v2

      - name: Build, Install, Test & Verify
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
          LIBRARY_TYPE: ${{ matrix.library_type }}
          WITH_OPENSSL: ${{ matrix.with_openssl }}
          COVERAGE: OFF
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        run: |
          ./scripts/do-all-unix.sh
