name: Nightly-macOS

on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [ 64 ]
        build_type: [ Debug, Release ]
        library_type: [ SHARED, STATIC ]
        with_openssl: [ OFF, ON ]  # TODO add ON after adding aws key

    runs-on: macos-latest

    steps:
      - name: Install Dependencies
        run: |
          brew install boost openssl thrift

      - uses: actions/checkout@v2

      - name: Build, Install, Test & Verify
        env:
          BIT_VERSION: ${{ matrix.arch }}
          BUILD_TYPE: ${{ matrix.build_type }}
          LIBRARY_TYPE: ${{ matrix.library_type }}
          WITH_OPENSSL: ${{ matrix.with_openssl }}
          COVERAGE: OFF
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        run: ./scripts/do-all-unix.sh
